# Generated by Django 4.1.4 on 2022-12-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='ex',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
