# Generated by Django 4.1.4 on 2022-12-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_ex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
