# Generated by Django 4.1.4 on 2022-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usermodel_is_staff_alter_usermodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
    ]
